services:
  rtabmap:
    build:
      context: .
      dockerfile: Dockerfile
    image: rtabmap-cuda:latest
    container_name: rtabmap
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../../data:/data
    working_dir: /data
    command: tail -f /dev/null
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
